// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStore.Services.CouponAPI.Data;

#nullable disable

namespace MyStore.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyStore.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "10OFF",
                            CreatedAt = new DateTime(2024, 5, 12, 16, 38, 58, 957, DateTimeKind.Local).AddTicks(7901),
                            DiscountAmount = 10.0,
                            MinAmount = 50
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "20OFF",
                            CreatedAt = new DateTime(2024, 5, 12, 16, 38, 58, 957, DateTimeKind.Local).AddTicks(7946),
                            DiscountAmount = 20.0,
                            MinAmount = 100
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "50OFF",
                            CreatedAt = new DateTime(2024, 5, 12, 16, 38, 58, 957, DateTimeKind.Local).AddTicks(7961),
                            DiscountAmount = 50.0,
                            MinAmount = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
